<!DOCTYPE library[
<!ELEMENT library (books,members,staffs,publisher)>
<!ELEMENT books (book1,book2)>
<!ELEMENT book1 (title,author,year,isbn,price)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT book2 (title,author,year,isbn,price)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT members (member1,member2)>
<!ELEMENT member1 (name,address,phone)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT member2 (name,address,phone)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT staffs (staff1,staff2)>
<!ELEMENT staff1 (name,address,phone)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT staff2 (name,address,phone)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT publisher (name,address,phone)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST book1 bookId CDATA #REQUIRED>
<!ATTLIST book2 bookId CDATA #REQUIRED>
<!ATTLIST member1 memberId CDATA #REQUIRED>
<!ATTLIST member2 memberId CDATA #REQUIRED>
<!ATTLIST staff1 staffId CDATA #REQUIRED>
<!ATTLIST staff2 staffId CDATA #REQUIRED>
<!ATTLIST publisher publisherId CDATA #REQUIRED>
]>

<library>
   <books>
     <book1 bookId="1">
       <title>Web Development Technologies</title>
       <author>Raja Ram</author>
       <year>1980</year>
       <isbn>38657655</isbn>
       <price>250</price>
     </book1>
      <book2 bookId="2">
       <title>Wings of Fire</title>
       <author>Abdul Kalam</author>
       <year>1990</year>
       <isbn>28657495</isbn>
       <price>350</price>
     </book2>
   </books>
   <members>
     <member1 memberId="101">
       <name>Jenni</name>
       <address>Busan</address>
       <phone>9848610171</phone>
     </member1>
     <member2 memberId="102">
       <name>Lisa</name>
       <address>New York</address>
       <phone>9356473774</phone>
     </member2>
   </members>
   <staffs>
     <staff1 staffId="501">
        <name>Rose</name>
        <address>Sydney</address>
        <phone>9215473774</phone>
     </staff1>
     <staff2 staffId="502">
        <name>Jisoo</name>
        <address>Seoul</address>
        <phone>913546987</phone>
     </staff2>
   </staffs>
   <publisher publishId="301">
     <name>Lily</name>
     <address>Kurnool</address>
     <phone>92154648864</phone>
   </publisher>
</library>